name: CI workflow

#Events
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
#JOBS
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    
    
    

